### PR TITLE
mostly maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- target Android Pie
- Java 1.8 compatibility
- migrate App to AppCompat
- migrate to AndroidX
- reformat code

### CODE REVIEW

**Comment by JanmanX** [comment]
Hi @TacoTheDank !
Thanks for the pull request, the changes look great!

However, I just need to add some minor styling fixes, as the window title bar appears in the EncryptActivity with this new update. Could you perhaps give me access to modify this pull request?

I think this is how you do it:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by TacoTheDank** [comment]
Lol I actually keep it on by default, so I think you're already allowed to edit it.
image

**Comment by TacoTheDank** [comment]
@JanmanX Did you get this message? .-.

**Comment by TacoTheDank** [comment]
Updated this again... you know you can just change the styling after merging, right?

**Comment by TacoTheDank** [comment]
No activity.

**Pull request closed without merging**
